.TH "todo" 3 "19 May 2008" "Edje" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBpage \fBEdje Library Documentation\fP \fP" 1c
See src/lib/edje_private.h for a list of FIXME's 
.PP
.PP
 
.IP "\fBpage \fBEdje Library Documentation\fP \fP" 1c
Complete documentation of API 
.PP
.PP
 
.IP "\fBpage \fBEdje Library Documentation\fP \fP" 1c
Bytecode language for extending programs... but what/how?
.PP
.PP

